server:
  port: 8800
spring:
  application:
    name: service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: lanxinservice
management:
  endpoints:
    web:
      exposure:
        include: '*'
